---

- hosts: localhost
  become: true
  tasks:

######################Chat Packages######################
### Discord based on distro ###
  - name: Installing Discord as snap package
    community.general.snap:
      name: discord
      channel: latest/stable
    when: ansible_distribution == 'Ubuntu'

  - name: Install Discord from Flathub
    community.general.flatpak:
      name: com.discordapp.Discord
      state: present
    when: ansible_distribution == 'Arch Linux'
    
  - name: Install Discord from RPMFusion Non-free
    ansible.builtin.package:
      name: discord
    when: ansible_distribution == 'Fedora'

### Teams based on distro ###
  - name: Installing Teams for Linux as a snap package
    community.general.snap:
      name: teams-for-linux
      channel: latest/stable
    when: ansible_distribution == 'Ubuntu'

  - name: Install Teams for Linux from Flathub
    community.general.flatpak:
      name: com.github.IsmaelMartinez.teams_for_linux
      state: present
    when: ansible_distribution == 'Arch Linux' or ansible_distribution == 'Fedora'
