code --install-extension absszero.vscode-laravel-goto --force &
code --install-extension alexcvzz.vscode-sqlite --force &
code --install-extension amiralizadeh9480.laravel-extra-intellisense --force &
code --install-extension batisteo.vscode-django --force &
code --install-extension bmewburn.vscode-intelephense-client --force &
code --install-extension bradlc.vscode-tailwindcss --force &
code --install-extension dsznajder.es7-react-js-snippets --force &
code --install-extension eamodio.gitlens --force &
code --install-extension esbenp.prettier-vscode --force &
code --install-extension humao.rest-client --force &
code --install-extension kreativ-software.csharpextensions --force &
code --install-extension meatrobot.tangotango --force &
code --install-extension ms-dotnettools.csdevkit --force &
code --install-extension ms-dotnettools.csharp --force &
code --install-extension ms-dotnettools.dotnet-interactive-vscode --force &
code --install-extension ms-dotnettools.vscode-dotnet-pack --force &
code --install-extension ms-dotnettools.vscode-dotnet-runtime --force &
code --install-extension ms-python.debugpy --force &
code --install-extension ms-python.python --force &
code --install-extension ms-python.vscode-pylance --force &
code --install-extension ms-toolsai.jupyter --force &
code --install-extension ms-toolsai.jupyter-keymap --force &
code --install-extension ms-toolsai.jupyter-renderers --force &
code --install-extension ms-toolsai.vscode-jupyter-cell-tags --force &
code --install-extension ms-toolsai.vscode-jupyter-slideshow --force &
code --install-extension ms-vscode-remote.remote-wsl --force &
code --install-extension mtxr.sqltools --force &
code --install-extension namesmt.blade-php --force &
code --install-extension onecentlin.laravel-blade --force &
code --install-extension onecentlin.laravel5-snippets --force &
code --install-extension patcx.vscode-nuget-gallery --force &
code --install-extension porifa.laraphense --force &
code --install-extension postman.postman-for-vscode --force &
code --install-extension rifi2k.format-html-in-php --force &
code --install-extension shufo.vscode-blade-formatter --force &
code --install-extension sidthesloth.html5-boilerplate --force &
code --install-extension tabnine.tabnine-vscode --force &
code --install-extension vscode-icons-team.vscode-icons --force &
code --install-extension xdebug.php-debug --force &
code --install-extension xdebug.php-pack --force &
code --install-extension zobo.php-intellisense --force
