---

- hosts: localhost
  become: true
  tasks:

######################Language Packages######################
### GoLang based on different distro ###
  - name: Installing golang
    ansible.builtin.package:
      name: golang
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Fedora'

  - name: Installing golang
    ansible.builtin.package:
      name: go
    when: ansible_distribution == 'Arch Linux'

### Java based on different distro ###
  - name: Installing java
    ansible.builtin.package:
      name: openjdk-21-jdk
    when: ansible_distribution == 'Ubuntu'

  - name: Installing java
    ansible.builtin.package:
      name: java-21-openjdk-portable-sources
    when: ansible_distribution == 'Fedora'

  - name: Installing java
    ansible.builtin.package:
      name: jdk21-openjdk
    when: ansible_distribution == 'Arch Linux'

### Clang based on different distro ###
  - name: Installing clangd-18 and tools
    ansible.builtin.package:
      name:
        - clangd-18
        - clang-tools-18
    when: ansible_distribution == 'Ubuntu'

  - name: Installing clang
    ansible.builtin.package:
      name:
        - clang
        - clang-tools-extra
    when: ansible_distribution == 'Fedora'

  - name: Installing clang
    ansible.builtin.package:
      name: clang
    when: ansible_distribution == 'Arch Linux'

### Python and pip based on different distro ###
  - name: Installing python3 venv and pip
    ansible.builtin.package:
      name:
        - python3-venv
        - python3-pip
    when: ansible_distribution == 'Ubuntu'

  - name: Installing python3 venv and pip
    ansible.builtin.package:
      name:
        - python
        - python-pylint-venv
        - python-pip
    when: ansible_distribution == 'Arch Linux'

  - name: Installing python3 venv and pip
    ansible.builtin.package:
      name:
        - python3
        - python3-pylint-venv
        - python3-pip
    when: ansible_distribution == 'Fedora'

### DotNet sdk based on distro ###
  - name: Installing DotNet
    ansible.builtin.package:
      name: dotnet-sdk-8.0
    when: ansible_distribution == 'Fedora'
