---

- hosts: localhost
  become: true
  tasks:

    - name: Installing htop
      package:
        name: htop

    - name: Installing i3
      ansible.builtin.package:
        name: i3

    - name: Installing rofi for nicer package searching in i3
      ansible.builtin.package:
        name: rofi

    - name: Installing arandr for i3 monitor configuration
      ansible.builtin.package:
        name: arandr

    - name: Installing curl
      ansible.builtin.package:
        name: curl

    - name: Installing golang
      ansible.builtin.package:
        name: golang

    - name: Installing cland-15 and tools
      ansible.builtin.package:
        name:
          - clangd-15
          - clang-tools-15

    - name: Installing python3-venv
      ansible.builtin.package:
        name: python3-venv

    - name: Installing emacs
      ansible.builtin.package:
        name: emacs

    - name: Installing ripgrep
      ansible.builtin.package:
        name: ripgrep

    - name: Installing fd-find
      ansible.builtin.package:
        name: fd-find

    - name: Installing silversearcher
      ansible.builtin.package:
        name: silversearcher-ag

  - name: Installing GIMP
    ansible.builtin.package:
      name: gimp

  - name: Installing OBS Studio and support packages
    ansible.builtin.package:
      name:
        - v4l2loopback-dkms
        - ffmpeg
        - obs-studio

    - name: Installing VLC media player
      ansible.builtin.package:
        name: vlc

    - name: Installing Terminator terminal
      ansible.builtin.package:
        name: terminator

    - name: Installing keepassxc
      ansible.builtin.package:
        name: keepassxc

    - name: Installing tmux
      ansible.builtin.package:
        name: tmux

    - name: Installing Flatpak
      andsible.builtin.package:
        name: flatpak

    - name: Add remote access to Flatpak
      ansible.builtin.shell:
        cmd: sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Installing Teams for Linux from Flathub
      community.general.flatpak:
        name: com.github.IsmaelMartinez.teams_for_linux
        state: latest
        
    - name: Installing Discord from Flathub
      community.general.flatpak:
        name: com.discordapp.Discord
        state: latest

    - name: Installing Visual Studio Code from Flathub
      community.general.flatpak:
        name: com.visualstudio.code
        state: latest

######################Snap Packages for Ubuntu Install######################
  # - name: Installing emacs as snap package
  #   community.general.snap:
  #     name: emacs
  #     classic: true
  #     channel: latest/stable

  # - name: Installing GIMP as snap package
  #   community.general.snap:
  #     name: gimp
  #     channel: latest/stable
      
  # - name: Installing obs-studio as a snap package
  #   community.general.snap:
  #     name: obs-studio
  #     channel: latest/stable

  # - name: Installing Visual Studio Code as snap package
  #   community.general.snap:
  #     name: code
  #     classic: true
  #     channel: latest/stable

  # - name: Installing Discord as snap package
  #   community.general.snap:
  #     name: discord
  #     channel: latest/stable
      
  # - name: Installing Teams for Linux as a snap package
  #   community.general.snap:
  #     name: teams-for-linux
  #     channel: latest/stable
